[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "mongoose", "connect-mongodb-session", "csrf-csrf"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
