[functions]
  directory = "netlify/functions"
  external_node_modules = [
    "express",
    "mongoose",
    "connect-mongodb-session",
    "helmet",
    "compression",
    "ejs"
  ]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
